---
bootstrap-servers: "rh-summit-cdcjli-j-icd-sb-es-a.bf2.kafka.rhcloud.com:443"
group-id: "pickup"
auto-offset-reset: "earliest"
security-protocol: "sasl_ssl"
sasl-mechanisms: "PLAIN"
sasl-username: "fa190c88-9f7b-4063-91ae-75a621a38b49"
sasl-password: "yFcvNqEhv13TzL6299sRV2yzjhq8bEUC"
topic: "pickup"