apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-retail-consumer
  namespace: pickup-management
spec:
  template:
    spec:
      containers:
      - name: edge-retail-consumer
        resources:
          limits:
            cpu: 250m
            memory: 256M
          requests:
            cpu: 50m
            memory: 32M