apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

images:
- name: edge-retail-consumer
  newName: quay.io/gbsalinetti/edge-retail-consumer
  newTag: latest

patchesStrategicMerge:
  - deployment.yaml